/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedStandingsIndexRouteImport } from './routes/_protected/standings/index'
import { Route as ProtectedMatchCenterIndexRouteImport } from './routes/_protected/match-center/index'
import { Route as ProtectedLeaderboardIndexRouteImport } from './routes/_protected/leaderboard/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedMatchCenterRecentRouteImport } from './routes/_protected/match-center/recent'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedStandingsIndexRoute = ProtectedStandingsIndexRouteImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMatchCenterIndexRoute =
  ProtectedMatchCenterIndexRouteImport.update({
    id: '/match-center/',
    path: '/match-center/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeaderboardIndexRoute =
  ProtectedLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMatchCenterRecentRoute =
  ProtectedMatchCenterRecentRouteImport.update({
    id: '/match-center/recent',
    path: '/match-center/recent',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match-center/recent': typeof ProtectedMatchCenterRecentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/leaderboard/': typeof ProtectedLeaderboardIndexRoute
  '/match-center/': typeof ProtectedMatchCenterIndexRoute
  '/standings/': typeof ProtectedStandingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match-center/recent': typeof ProtectedMatchCenterRecentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/leaderboard': typeof ProtectedLeaderboardIndexRoute
  '/match-center': typeof ProtectedMatchCenterIndexRoute
  '/standings': typeof ProtectedStandingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/match-center/recent': typeof ProtectedMatchCenterRecentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/leaderboard/': typeof ProtectedLeaderboardIndexRoute
  '/_protected/match-center/': typeof ProtectedMatchCenterIndexRoute
  '/_protected/standings/': typeof ProtectedStandingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/match-center/recent'
    | '/api/auth/$'
    | '/dashboard/'
    | '/leaderboard/'
    | '/match-center/'
    | '/standings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/match-center/recent'
    | '/api/auth/$'
    | '/dashboard'
    | '/leaderboard'
    | '/match-center'
    | '/standings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/match-center/recent'
    | '/api/auth/$'
    | '/_protected/dashboard/'
    | '/_protected/leaderboard/'
    | '/_protected/match-center/'
    | '/_protected/standings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/standings/': {
      id: '/_protected/standings/'
      path: '/standings'
      fullPath: '/standings/'
      preLoaderRoute: typeof ProtectedStandingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/match-center/': {
      id: '/_protected/match-center/'
      path: '/match-center'
      fullPath: '/match-center/'
      preLoaderRoute: typeof ProtectedMatchCenterIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leaderboard/': {
      id: '/_protected/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof ProtectedLeaderboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/match-center/recent': {
      id: '/_protected/match-center/recent'
      path: '/match-center/recent'
      fullPath: '/match-center/recent'
      preLoaderRoute: typeof ProtectedMatchCenterRecentRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedMatchCenterRecentRoute: typeof ProtectedMatchCenterRecentRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedLeaderboardIndexRoute: typeof ProtectedLeaderboardIndexRoute
  ProtectedMatchCenterIndexRoute: typeof ProtectedMatchCenterIndexRoute
  ProtectedStandingsIndexRoute: typeof ProtectedStandingsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedMatchCenterRecentRoute: ProtectedMatchCenterRecentRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedLeaderboardIndexRoute: ProtectedLeaderboardIndexRoute,
  ProtectedMatchCenterIndexRoute: ProtectedMatchCenterIndexRoute,
  ProtectedStandingsIndexRoute: ProtectedStandingsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
